name: onlook

services:
  web-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_DATABASE_URL=${SUPABASE_DATABASE_URL}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
        - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - CSB_API_KEY=${CSB_API_KEY}
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_SECRET=${GITHUB_SECRET}
        - GITHUB_OAUTH_REDIRECT_URI=${GITHUB_OAUTH_REDIRECT_URI}
        - FREESTYLE_API_KEY=${FREESTYLE_API_KEY}
        - NEXT_PUBLIC_HOSTING_DOMAIN=${NEXT_PUBLIC_HOSTING_DOMAIN}
        - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
        - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
        - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
    env_file:
      - apps/web/client/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    command: bun run start:standalone
